var css = '<style type="text/css">*{margin: 0;padding: 0;font-family: "Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif;font-size: 100%;line-height: 1.6;}img{max-width: 100%;}body{-webkit-font-smoothing: antialiased;-webkit-text-size-adjust: none;width: 100%!important;height: 100%;}a{color: #348eda;}.btn-primary{text-decoration: none;color: #FFF;background-color: #348eda;border: solid #348eda;border-width: 10px 20px;line-height: 2;font-weight: bold;margin-right: 10px;text-align: center;cursor: pointer;display: inline-block;border-radius: 25px;}.btn-secondary{text-decoration: none;color: #FFF;background-color: #aaa;border: solid #aaa;border-width: 10px 20px;line-height: 2;font-weight: bold;margin-right: 10px;text-align: center;cursor: pointer;display: inline-block;border-radius: 25px;}.last{margin-bottom: 0;}.first{margin-top: 0;}.padding{padding: 10px 0;}table.body-wrap{width: 100%;padding: 20px;}table.body-wrap .container{border: 1px solid #f0f0f0;}table.footer-wrap{width: 100%;clear: both!important;}.footer-wrap .container p{font-size: 12px;color: #666;}table.footer-wrap a{color: #999;}h1, h2, h3{font-family: "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;line-height: 1.1;margin-bottom: 15px;color: #000;margin: 40px 0 10px;line-height: 1.2;font-weight: 200;}h1{font-size: 36px;}h2{font-size: 28px;}h3{font-size: 22px;}p, ul, ol{margin-bottom: 10px;font-weight: normal;font-size: 14px;}ul li, ol li{margin-left: 5px;list-style-position: inside;}.container{display: block!important;max-width: 600px!important;margin: 0 auto!important;clear: both!important;}.body-wrap .container{padding: 20px;}.content{max-width: 600px;margin: 0 auto;display: block;}.content table{width: 100%;}</style>';

exports.signup = {
    from: 'contact@synchronise.io',
    subject: 'Welcome to Synchronise',
    body: css + '<table class="body-wrap"><tbody><tr><td>&nbsp;</td><td bgcolor="#FFFFFF" class="container"><div class="content"><table><tbody><tr><td><h2>Hi there,</h2><p>Ready to have some fun with components&nbsp;? I guess you are as excited as we are to get started !</p><h3 style="text-align: center;">Do not&nbsp;loose a minute and discover all the possibilites that Synchronise has to offer.</h3><p>&nbsp;</p><p>Dive into our documentation&nbsp;to discover all the details :&nbsp;</p><table><tbody><tr><td class="padding"><p style="text-align: center;"><a class="btn-primary" href="https://www.synchronise.io/docs?ref=metric1">Go to the documentation</a></p></td></tr></tbody></table><p>Have a question or a suggestion ? Feel free to send us&nbsp;an email at&nbsp;<a href="mailto:contact@synchronise.io">contact@synchronise.io</a></p><p>Thanks, and have a lovely day.</p><p><a href="http://twitter.com/synchroniseio">Follow @synchroniseio on Twitter</a></p></td></tr></tbody></table></div></td><td>&nbsp;</td></tr></tbody></table><p>&nbsp;</p><p>&nbsp;</p>'
};

exports.recoverPassword = {
    from : 'noreply@synchronise.io',
    subject: 'Recover password',
    body: css + '<center><img src="https://images.synchronise.io/synchroniseFullBlack.png" style="height: 100px; margin-top: 50px"></center><table class="body-wrap" style="margin-top: -22px"><tbody><tr><td>&nbsp;</td><td bgcolor="#FFFFFF" class="container"><div class="content"><table><tbody><tr><td><h2>Well well well,</h2><p>I see you have your head in the clouds. Lucky you we are in a good mood and we will help you recover your password.</p><h3 style="text-align: center;"><a href="https://www.synchronise.io/recover_password/{{TOKEN}}">Click this link to recover your password</a></h3><p>&nbsp;</p>'
};
